In [50]:
import pandas as pd

In [51]:
df = pd.read_csv(r'C:\\Users\\Muhammad Saad\\OneDrive\\Desktop\\bitcoin price prediction\\bitcoin_price_prediction Dataset.csv')

In [52]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...
2708,2022-02-15,42586.464844,44667.218750,42491.035156,44575.203125,44575.203125,22721659051
2709,2022-02-16,44578.277344,44578.277344,43456.691406,43961.859375,43961.859375,19792547657
2710,2022-02-17,43937.070313,44132.972656,40249.371094,40538.011719,40538.011719,26246662813
2711,2022-02-18,40552.132813,40929.152344,39637.617188,40030.976563,40030.976563,23310007704
2712,2022-02-19,40022.132813,40246.027344,40010.867188,40126.429688,40126.429688,22263900160

In [53]:
df[df['Close'] == df['Adj Close']].shape

(2713, 7)

In [54]:
df.head(1)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800

In [55]:
df['Date'] = df['Date'].astype('datetime64[ns]')

In [56]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day

In [57]:
df.drop(columns=['Adj Close','Date'], inplace=True)

In [58]:
df.head()

         Open        High         Low       Close    Volume  year  month  day
0  465.864014  468.174011  452.421997  457.334015  21056800  2014      9   17
1  456.859985  456.859985  413.104004  424.440002  34483200  2014      9   18
2  424.102997  427.834991  384.532013  394.795990  37919700  2014      9   19
3  394.673004  423.295990  389.882996  408.903992  36863600  2014      9   20
4  408.084991  412.425995  393.181000  398.821014  26580100  2014      9   21